# This file was generated by wxPython's wscript.

VERSION_STRING    = '4.2.1'
MAJOR_VERSION     = 4
MINOR_VERSION     = 2
RELEASE_NUMBER    = 1
BUILD_TYPE        = 'release'

VERSION = (MAJOR_VERSION, MINOR_VERSION, RELEASE_NUMBER, '')
