"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PS5-Toolbox.py']
DATA_FILES = ['mac.icns']
OPTIONS = {
    'packages': ['requests', 'charset_normalizer', 'urllib3'],
    'includes': ['requests', 'charset_normalizer', 'urllib3'],
    'iconfile': 'mac.icns',
    'plist': {
        'CFBundleDevelopmentRegion': 'English',
        'CFBundleName': 'PS5Toolbox',
        'CFBundleDisplayName': 'PS5Toolbox',
        'CFBundleGetInfoString': 'PS5Toolbox',
        'CFBundleIdentifier': 'com.github.ps5-toolbox',
        'CFBundleVersion': '0.3.0',
        'CFBundleShortVersionString': '0.3.0',
        'CFBundleIconFile': 'mac.icns',
        'NSHighResolutionCapable': 'True',
        'NSHumanReadableCopyright': 'Copyright 2024 TechCentreUK',
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
